name: Deploy

on:
  push:
    branches:
      - master
    tags:
      - latest
      - v*

jobs:

  ghcr:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure
        run: |
          echo "REF=${GITHUB_REF##refs/*/}" >> $GITHUB_ENV
          ./bootstrap.sh
          ./configure  \
            GITCLIFF=: \
            --enable-developer-mode \
            --without-{bash,fish,zsh}-completion-dir
      - name: Publish Docker Image to GH Container Registry
        run: |
          make docker-build-push
        env:
          DOCKER_REGISTRY: ghcr.io
          DOCKER_REPO: ${{ github.repository }}
          DOCKER_TAG: ${{ env.REF }}
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PAT: ${{ secrets.GHCR_PAT }}
